handle $ORIGIN in RPATH

diff --git a/lddsafe b/lddsafe
--- a/lddsafe
+++ b/lddsafe
@@ -12,7 +12,7 @@ export LANG=C
 # Print error and exit.
 die()
 {
-	echo "ERROR: $1" 1>&2
+	printf "ERROR: $1\n" 1>&2
 	exit 1
 }
 
@@ -49,7 +49,7 @@ done
 shift $((OPTIND-1))
 
 if [ $# -eq 0 ]; then
-	echo "Usage: $( basename $0 ) [-n] [-q] FILE..." 2>&1
+	printf "Usage: $( basename $0 ) [-n] [-q] FILE...\n" 2>&1
 	exit 1
 fi
 for arg in "$@"; do
@@ -59,7 +59,7 @@ done
 # Recursively print the list of files included from /etc/ld.so.conf.
 ld_so_conf_deps()
 {
-	echo "$1"
+	printf "$1\n"
 	dirname="$( dirname "$1" )"
 	patterns="$( sed -n 's/^include[\ \t]\+\(.\+\)$/\1/p' "$1" )"
 	set -o noglob
@@ -98,7 +98,7 @@ searchlib()
 			break
 		fi
 	done
-	[ $found -eq 1 ] && echo "$path" | sed 's#//*#/#g'
+	[ $found -eq 1 ] && realpath "$path" | sed 's#//*#/#g'
 }
 
 # Print dependency results, recursively.
@@ -113,14 +113,14 @@ recursivedeps()
 			file=$(searchlib "$lib")
 			if [ "$file" ]; then
                 if [ $quiet -eq 1 ] ; then
-                    echo "$file"
+                    printf "$file\n"
                 else
-				    echo "	$lib => $file"
+				    printf "	$lib => $file\n"
                 fi
 				[ $recursive -eq 1 ] && recursivedeps "$file"
 			else
                 if [ $quiet -eq 0 ]; then
-				    echo "	$lib => not found"
+				    printf "	$lib => not found\n"
                 fi
 			fi
 		fi
@@ -131,17 +131,17 @@ recursivedeps()
 # Search symbol names in library directories.
 for arg in "$@"; do
 	# Print file name when more than one file given.
-	[ $# -gt 1 ] && echo "${arg}:"
+	[ $# -gt 1 ] && printf "${arg}:\n"
 
 	# Set appropriate library search directories.
 	class=$( readelf -h $arg 2>/dev/null | \
 		 sed -n 's/^[ \t]*Class:[\ \t]\+\(.\+\)/\1/p' )
 	if [ -z "$class" ]; then
-		echo "$arg: not an ELF file" 2>&1
+		printf "$arg: not an ELF file\n" 2>&1
 		continue
 	fi
 	if [ $class != ELF32 -a $class != ELF64 ]; then
-		echo "$arg: unknown ELF format" 2>&1
+		printf "$arg: unknown ELF format\n" 2>&1
 		continue
 	fi
 	if [ $class == ELF64 ]; then
@@ -157,7 +157,9 @@ for arg in "$@"; do
 			stdlibs="/lib /usr/local/lib /usr/lib"
 		fi
 	fi
-	LIBDIRS="$LD_LIBRARY_PATH_LIBS $MORELIBDIRS $stdlibs"
+    RPATH=$(objdump -p "$arg" | sed -n 's,^ *RPATH \+\([^ ]\+\) *$,\1,p' | tr ':' ' ' | sed "s,\$ORIGIN,$(dirname $(realpath ${arg})),g")
+    RUNPATH=$(objdump -p "$arg" | sed -n 's,^ *RUNPATH \+\([^ ]\+\) *$,\1,p' | tr ':' ' ' | sed "s,\$ORIGIN,$(dirname $(realpath ${arg})),g")
+	LIBDIRS="$RPATH $RUNPATH $LD_LIBRARY_PATH_LIBS $MORELIBDIRS $stdlibs"
 
 	# Get a unique list of library dependencies for this argument.
 	recursivedeps "$arg"
